### ISSUE TITLE
When going through portals your scale do not change. (Forge)

### ISSUE THREAD

**Issue by patfr** [Virtuoel/Pehkui#113] opened 2021-05-17 13:23 UTC
So i have installed forge version of both immersive portals and pehkui for forge and when i go through a portal the camera's view changes scale and height going through it but once you get through the camera jumps back to show the world in the normal size and scale and your still 2 blocks high.

**Comment by Gregdabrat** [comment] 2021-05-23 21:09
Yes i have this too i just wanna do it with bits and chisels rip

**Comment by Virtuoel** [comment] 2021-05-24 17:43
Duplicate of https://github.com/qouteall/ImmersivePortalsModForForge/issues/243

**Closed as completed by Virtuoel** 2021-05-24 17:43 UTC

**Comment by Virtuoel** [comment] 2022-10-30 16:56
Tested with latest Immersive Portals for 1.18.2 Forge and it appears to be working now.
