### ISSUE TITLE
Won't work with the latest Cloth version

### ISSUE THREAD

**Issue by Kirbykraze** [Virtuoel/Pehkui#33] opened 2021-02-08 00:24 UTC
I'm not quite sure how to install this mod, but when I put Pehkui-1.7.1+21w03a-sources.jar into the mods folder, it instantly crashes with exit code 0. But if I put Pehkui-1.7.1+21w03a.jar into the mods folder, it doesn't recognize it at all. help?

How to replicate:
1. put Pehkui-1.7.1+21w03a-sources.jar or Pehkui-1.7.1+21w03a.jar into the mods folder in .minecraft
2. Boot up the latest cloth version

**Comment by trqzh** [comment] 2021-02-14 17:21
not sure if i'm doing something differently but i have cloth and pehkui both installed and it works fine

**Comment by Dapperbot28** [comment] 2021-02-27 19:18
This is also happening for me. I have cloth, fabric and pehkui all installed correctly. It simply does not load.

**Comment by Virtuoel** [comment] 2021-03-02 17:43
I am unable to reproduce this issue. Can you try again with Pehkui 1.8.0? If you still have the issue, make sure to also include the exact versions of Minecraft, Fabric Loader, Fabric API, and versions of any other mods that you're using.

**Comment by Testsr** [comment] 2021-03-07 09:03
@Kirbykraze and @Dapperbot28 try /scale in a Minecraft World. If that command does not work, then we have an issue. If it does work, the mod is installed correctly, and this issue can be closed.

**Comment by Virtuoel** [comment] 2021-03-11 15:46
Should now be resolved in 1.9.0.

**Closed as completed by Virtuoel** 2021-03-11 15:46 UTC
