### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by camblycreeper** [Virtuoel/Pehkui#132] opened 2021-06-03 09:48 UTC
I've downloaded the latest forge version of the mod for 1.6.5 several times, 
I see it in the folder: "Pehkui-2.2.0+1.16.5-forge"
I've planted it in the folder by hand after it failed to do anything when I installed it on the curseforge launcher.
I have immersive portals and there is no sticks, and the portals don't change any scale whatsoever, as if the mod isn't there, WHICH IT IS. 
The portals work, but they don't resize anything, and there is no sticks that edit the portals and things (In case they should appear because pehkui and Immersive Portals)
I also could not find any commands that imply Pehkui is even there.
Either I'm completly stupid, Immersive portals no longer covers Pehkui, or this Forge version for 1.16.5 isn't working.

**Comment by Virtuoel** [comment] 2021-06-14 18:52
Duplicate of qouteall/ImmersivePortalsModForForge#243

**Closed as completed by Virtuoel** 2021-06-14 18:52 UTC
