### ISSUE TITLE
[Bug]: Entities are interactable behind (and take priority over) blocks that are in front of them

### ISSUE THREAD

**Issue by Smearfo** [Virtuoel/Pehkui#196] opened 2021-10-07 17:55 UTC
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

Forge 36.2.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Entities that are occluded by blocks are still visible on tooltips like The One Probe, and can still be interacted with through punching/right clicking, as well as taking interaction priority over the blocks they are behind, preventing you from breaking or activating the blocks.

**Steps to reproduce:**

1. Build 1-block thick wall
2. Place cow behind wall
3. Stand on other side
4. Milk cow through the wall

### Full list of installed mods

Pehkui-2.4.0+1.16.5-forge
theoneprobe-1.16-3.1.4

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment] 2021-10-07 18:10
Duplicate of #192

**Closed as completed by Virtuoel** 2021-10-07 18:10 UTC
Labels: bug
