### ISSUE TITLE
[Bug]: Pekhui bad mixin crash

### ISSUE THREAD

**Issue by someaddons** [Virtuoel/Pehkui#347] opened 2022-12-07 12:05 UTC
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

43.1.65

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Pekhui + Forge crashes with the step_height mixin, might be because its trying to use yarn names

### Full list of installed mods and their version numbers

Pehkui-3.6.0+1.19.2-forge.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

https://gist.github.com/someaddons/c265fe774306d11b0d83dd6153d93c0b

[07Dec2022 13:01:27.333] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Pixblockus, --version, 1.19.2, --gameDir, E:/Games/Minecraft/MultiMC/instances/1.19.2.Forge/.minecraft, --assetsDir, E:/Games/Minecraft/MultiMC/assets, --assetIndex, 1.19, --uuid, c1a5dd12a6d140ecaacfae047ba842f3, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.1.65, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, --width, 854, --height, 480]
[07Dec2022 13:01:27.337] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.4 by Eclipse Adoptium; OS Windows 10 arch amd64 version 10.0
[07Dec2022 13:01:27.441] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/Games/Minecraft/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23141!/ Service=ModLauncher Env=CLIENT
[07Dec2022 13:01:27.664] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file E:\Games\Minecraft\MultiMC\libraries\net\minecraftforge\fmlcore\1.19.2-43.1.65\fmlcore-1.19.2-43.1.65.jar is missing mods.toml file
[07Dec2022 13:01:27.669] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file E:\Games\Minecraft\MultiMC\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.1.65\javafmllanguage-1.19.2-43.1.65.jar is missing mods.toml file
[07Dec2022 13:01:27.674] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file E:\Games\Minecraft\MultiMC\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.1.65\lowcodelanguage-1.19.2-43.1.65.jar is missing mods.toml file
[07Dec2022 13:01:27.679] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file E:\Games\Minecraft\MultiMC\libraries\net\minecraftforge\mclanguage\1.19.2-43.1.65\mclanguage-1.19.2-43.1.65.jar is missing mods.toml file
[07Dec2022 13:01:27.729] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[07Dec2022 13:01:28.367] [main/INFO] [mixin/]: Compatibility level JAVA_8 specified by pehkui.mixins.json is lower than the default level supported by the current mixin service (JAVA_16).
[07Dec2022 13:01:28.369] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2, --gameDir, E:\Games\Minecraft\MultiMC\instances\1.19.2.Forge\.minecraft, --assetsDir, E:\Games\Minecraft\MultiMC\assets, --uuid, c1a5dd12a6d140ecaacfae047ba842f3, --username, Pixblockus, --assetIndex, 1.19, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[07Dec2022 13:01:28.411] [main/INFO] [mixin/]: Attempting to load Fernflower decompiler (Threaded mode)
[07Dec2022 13:01:28.412] [main/INFO] [mixin/]: Fernflower could not be loaded, exported classes will not be decompiled. NoClassDefFoundError: org/jetbrains/java/decompiler/main/extern/IResultSaver
[07Dec2022 13:01:28.419] [main/INFO] [mixin/]: Preparing mixins for MixinEnvironment[DEFAULT]
[07Dec2022 13:01:28.420] [main/INFO] [mixin/]: Selecting config pehkui.mixins.json
[07Dec2022 13:01:28.430] [main/INFO] [mixin/]: Preparing pehkui.mixins.json (193)
[07Dec2022 13:01:28.788] [main/INFO] [mixin/]: Prepared 113 mixins in 0,367 sec (3,2ms avg) (0ms load, 0ms transform, 0ms plugin)
[07Dec2022 13:01:29.344] [pool-3-thread-1/INFO] [mixin/]: Mixing compat116plus.AbstractBlockStateMixin from pehkui.mixins.json into net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase
[07Dec2022 13:01:29.394] [pool-3-thread-1/INFO] [mixin/]: Mixing EntityMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
[07Dec2022 13:01:29.431] [pool-3-thread-1/INFO] [mixin/]: Mixing compat116plus.EntityMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
[07Dec2022 13:01:29.432] [pool-3-thread-1/INFO] [mixin/]: Mixing compat117plus.EntityMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
[07Dec2022 13:01:29.435] [pool-3-thread-1/INFO] [mixin/]: Mixing step_height.EntityMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
[07Dec2022 13:01:29.436] [pool-3-thread-1/INFO] [mixin/]: Mixing compat117plus.patchwork.compat.EntityCalculateDimensionsMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
[07Dec2022 13:01:29.436] [pool-3-thread-1/INFO] [mixin/]: Renaming synthetic method lambda$pehkui$calculateDimensions$0(Lnet/minecraft/world/entity/Entity;DLnet/minecraft/world/phys/Vec3;)V to md10a70a$lambda$pehkui$calculateDimensions$0$0 in pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin
[07Dec2022 13:01:29.524] [pool-3-thread-1/FATAL] [MixinProcessor/]: /***********************************************************************************************************************************************************************/
[07Dec2022 13:01:29.524] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*                                                                            Invalid Mixin                                                                            */
[07Dec2022 13:01:29.524] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*---------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[07Dec2022 13:01:29.524] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     Action : APPLY                                                                                                                                                  */
[07Dec2022 13:01:29.524] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*      Mixin : virtuoel.pehkui.mixin.step_height.EntityMixin                                                                                                          */
[07Dec2022 13:01:29.525] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     Config : pehkui.mixins.json                                                                                                                                     */
[07Dec2022 13:01:29.525] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*      Phase : DEFAULT                                                                                                                                                */
[07Dec2022 13:01:29.525] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*---------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[07Dec2022 13:01:29.525] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException                                                                                      */
[07Dec2022 13:01:29.525] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*---------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[07Dec2022 13:01:29.526] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     Injection validation failed: Redirector pehkui$adjustMovementForCollisions$stepHeight(Lnet/minecraft/world/entity/Entity;)F in                                  */
[07Dec2022 13:01:29.526] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     pehkui.mixins.json:step_height.EntityMixin expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json [INJECT Applicator    */
[07Dec2022 13:01:29.526] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     Phase -> pehkui.mixins.json:step_height.EntityMixin -> Apply Injections ->  -> PostInject ->                                                                    */
[07Dec2022 13:01:29.526] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     pehkui.mixins.json:step_height.EntityMixin->@Redirect::pehkui$adjustMovementForCollisions$stepHeight(Lnet/minecraft/world/entity/Entity;)F]                     */
[07Dec2022 13:01:29.526] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*---------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[07Dec2022 13:01:29.526] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Redirector                                             */
[07Dec2022 13:01:29.526] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     pehkui$adjustMovementForCollisions$stepHeight(Lnet/minecraft/world/entity/Entity;)F in pehkui.mixins.json:step_height.EntityMixin expected 1 invocation(s)      */
[07Dec2022 13:01:29.526] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     but 0 succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json [INJECT Applicator Phase -> pehkui.mixins.json:step_height.EntityMixin -> Apply           */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     Injections ->  -> PostInject ->                                                                                                                                 */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*     pehkui.mixins.json:step_height.EntityMixin->@Redirect::pehkui$adjustMovementForCollisions$stepHeight(Lnet/minecraft/world/entity/Entity;)F]                     */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:463)                          */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)               */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)     */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)           */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)                */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)                          */
[07Dec2022 13:01:29.527] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)                    */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)                            */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)                     */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)                    */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)          */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)                      */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)                                         */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)             */
[07Dec2022 13:01:29.528] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)                                                           */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)                                                     */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)                                                          */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)                                                               */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)                                                               */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)                                                                                             */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         TRANSFORMER/forge@43.1.65/net.minecraftforge.registries.GameData.init(GameData.java:108)                                                                    */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         TRANSFORMER/forge@43.1.65/net.minecraftforge.registries.GameData.<clinit>(GameData.java:93)                                                                 */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.forge(Registry.java:435)                                                                           */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.forge(Registry.java:419)                                                                           */
[07Dec2022 13:01:29.529] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.<clinit>(Registry.java:186)                                                                        */
[07Dec2022 13:01:29.530] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43)                                                                    */
[07Dec2022 13:01:29.530] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.lambda$run$0(Main.java:145)                                                                     */
[07Dec2022 13:01:29.530] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)                                                                           */
[07Dec2022 13:01:29.530] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                          */
[07Dec2022 13:01:29.530] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                   */
[07Dec2022 13:01:29.530] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                   */
[07Dec2022 13:01:29.531] [pool-3-thread-1/FATAL] [MixinProcessor/]: /*         java.base/java.lang.Thread.run(Thread.java:833)                                                                                                             */
[07Dec2022 13:01:29.531] [pool-3-thread-1/FATAL] [MixinProcessor/]: /***********************************************************************************************************************************************************************/
[07Dec2022 13:01:29.531] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed pehkui.mixins.json:step_height.EntityMixin -> net.minecraft.world.entity.Entity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Injection validation failed: Redirector pehkui$adjustMovementForCollisions$stepHeight(Lnet/minecraft/world/entity/Entity;)F in pehkui.mixins.json:step_height.EntityMixin expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json [INJECT Applicator Phase -> pehkui.mixins.json:step_height.EntityMixin -> Apply Injections ->  -> PostInject -> pehkui.mixins.json:step_height.EntityMixin->@Redirect::pehkui$adjustMovementForCollisions$stepHeight(Lnet/minecraft/world/entity/Entity;)F]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Redirector pehkui$adjustMovementForCollisions$stepHeight(Lnet/minecraft/world/entity/Entity;)F in pehkui.mixins.json:step_height.EntityMixin expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json [INJECT Applicator Phase -> pehkui.mixins.json:step_height.EntityMixin -> Apply Injections ->  -> PostInject -> pehkui.mixins.json:step_height.EntityMixin->@Redirect::pehkui$adjustMovementForCollisions$stepHeight(Lnet/minecraft/world/entity/Entity;)F]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:463) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.registries.GameData.init(GameData.java:108) ~[forge-1.19.2-43.1.65-universal.jar%23153!/:?]
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:93) ~[forge-1.19.2-43.1.65-universal.jar%23153!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:435) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:419) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:186) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?]
	at net.minecraft.client.main.Main.lambda$run$0(Main.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23148!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Virtuoel** [comment] 2022-12-07 14:28
Only am able to reproduce if mixin debug is enabled like it is in that log. Does not appear to occur if mixin debug is unset. Not sure why mixin debug would ignore the `require = 0`, might be worth reporting to mixin?

**Comment by someaddons** [comment] 2022-12-08 12:44
I'm not sure why it is hiding the error when starting without the debug flag, I guess it depends on how forge loads mixins, though nonetheless the mixin itself is still broken as it can't apply

**Comment by Virtuoel** [comment] 2022-12-17 16:30
Turns out mixin in debug mode uses `expect` in addition to `require`.
Setting both `= 0` fixes this crash, will be resolved in the next release.

**Comment by Virtuoel** [comment] 2022-12-19 01:22
Should now be resolved as of 3.6.1.

**Closed as completed by Virtuoel** 2022-12-19 01:22 UTC
Labels: bug
