### ISSUE TITLE
[Bug]: Unable to join server at all after becoming too small

### ISSUE THREAD

**Issue by ghost** [Virtuoel/Pehkui#380] opened 2023-02-25 12:51 UTC
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

0.14.14

### Fabric API version

0.73.2

### In what kind of world or server did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

i made a 1 pixel high immersive portal, after i went through the bigger one, i was kicked out and was unable to login back to my server because of an internal server error. I had my friend delete the portal, and when i tried to join this was the error message: Registry remapping failed: RE
Received ID map for minecraft:command_argument_type contains IDs unknown to the receiver! - pehkui:scale_type  - pehkui:scale_operation  - pehkui:scale_easing  - pehkui:scale_modifier

If i delete pehkui from the server, i can join normally. I tried resetting my size by teleporting through dimension but i still got the same error message when enabling pehkui again. I tried to find a pehkui data folder or something like that so i could try to reset pehkui comepletely, but i couldnt find the data file.

Error message:
![image](https://user-images.githubusercontent.com/35664231/221356999-9439ab9e-a74c-4afb-bc12-939665571e89.png)

### Full list of installed mods and their version numbers

alternate-current-mc1.19-1.4.0.jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.4.62-fabric.jar
badpackets-fabric-0.2.1.jar
bclib-2.1.5.jar
BetterAnimationsCollection-v4.0.5-1.19.2-Fabric.jar
better-end-2.1.2.jar
BetterF3-4.0.0-Fabric-1.19.2.jar
better-nether-7.1.2.jar
Bookshelf-Fabric-1.19.2-16.2.17.jar
BuildingWands_mc1.19.2-2.6.3_release-fabric.jar
CITResewn-1.1.2+1.19.2.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
colorfulsubtitles-1.0.0.jar
connectivity-fabric-1.19.2-3.8.jar
Controlling-fabric-1.19.2-10.0+7.jar
createaddition+1.19.2-1.19.2-20221218a.jar
createdeco-1.2.12-1.19.2.jar
create-fabric-0.5.0g-796+1.19.2.jar
create-stuff-additions1.19.2_v2.0.2a.jar
cullleaves-fabric-3.0.1.jar
cultural-delights-fabric-0.14.9+1.19.2.jar
dark-loading-screen-1.6.12.jar
DarkUtilities-Fabric-1.19.2-13.1.7.jar
Debugify-2.8.0.jar
Decorative+Blocks-fabric-1.19.2-3.0.0.jar
deepslatecutting-fabric-1.5.0.jar
dynamic-fps-2.2.0.jar
enchanted-vertical-slabs-1.6.jar
entityculling-fabric-1.5.2-mc1.19.jar
everycomp-1.19.2-2.2.2-fabric.jar
evs-betterend-1.1.0.jar
expandeddelight-0.2.5.jar
expandedstorage-8.0.5+1.19.2-fabric.jar
extendedflywheels-1.19.2-0.5.0.g-1.2.5.1.jar
fabric-api-0.73.2+1.19.2.jar
fabric-language-kotlin-1.8.7+kotlin.1.7.22.jar
fallingleaves-1.13.0+1.19.2.jar
FallingTree-1.19.2-3.10.0.jar
Faraway_beacons_fabric_1.19.2.jar
farmers-delight-fabric-1.19.X-1.3.9.jar
farmersknives-2.3.jar
ferritecore-5.0.3-fabric.jar
filenames.txt
ftb-chunks-fabric-1902.3.13-build.207.jar
ftb-library-fabric-1902.3.10-build.162.jar
ftb-teams-fabric-1902.2.10-build.76.jar
ftb-ultimine-fabric-1902.3.5-build.65.jar
geckolib-fabric-1.19-3.1.38.jar
immersive-portals-2.3.1-mc1.19.2-fabric.jar
indium-1.0.9+mc1.19.2.jar
IngredientExtensionAPI-fabric-1.19.2-3.0.6.jar
InventorySorter-1.8.10-1.19.jar
krypton-0.2.1.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.19.2-0.10.4.jar
mcw-bridges-2.0.6-mc1.19.2fabric.jar
mcw-doors-1.0.8fabric-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2fabric.jar
mcw-lights-1.0.5-mc1.19.2fabric.jar
mcw-paths-1.0.2fabric-mc1.19.2.jar
mcw-trapdoors-1.0.8-mc1.19.2fabric.jar
memoryleakfix-1.19.3-0.7.0.jar
MixinConflictHelper-1.2.0.jar
mixintrace-1.1.1+1.17.jar
modmenu-4.1.2.jar
moonlight-1.19.2-2.2.9-fabric.jar
morechathistory-1.19.1-1.1.1.jar
MouseTweaks-fabric-mc1.19-2.22.jar
NethersDelight-1.0.1.jar
New Text Document.txt
owo-lib-0.8.5+1.19.jar
Patchouli-1.19.2-77-FABRIC.jar
Pehkui-3.7.01.14.4-1.19.3.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
rer-2.6.0.jar
rhino-fabric-1902.2.2-build.264.jar
RoughlyEnoughItems-9.1.580.jar
RoughlyEnoughLootTables-1.19-1.0.jar
RoughlyEnoughProfessions-fabric-1.19.2-1.1.3.jar
screenshot-to-clipboard-1.0.9-fabric.jar
sodium-extra-0.4.16+mc1.19.2-build.90.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
spark-1.10.17-fabric.jar
starlight-1.1.1+fabric.ae22326.jar
Structory_Towers_1.19_v1.0.1.jar
Structory-1.19-v1.3.jar
supplementaries-1.19.2-2.2.50-fabric.jar
TerraBlender-fabric-1.19.2-2.0.1.130.jar
toms_storage_fabric-1.19-1.4.5.jar
Towns-and-Towers-1.19.2-1.9.jar
vanilla-hammers-3.5.0-1.19.2.jar
weaponmaster-multi-fabric-1.19-3.0.2.jar
wraith-waystones-3.0.5+mc1.19.2.jar
wthit-fabric-5.13.4.jar
Xaeros_Minimap_22.17.1_Fabric_1.19.1.jar
XaerosWorldMap_1.28.9_Fabric_1.19.1.jar
YetAnotherConfigLib-1.7.1.jar
youre-in-grave-danger-1.4.6.jar
YungsApi-1.19.2-Fabric-3.8.2.jar
YungsBetterDesertTemples-1.19.2-Fabric-2.2.1.jar
YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0.jar
YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
YungsBridges-1.19.2-Fabric-3.1.0.jar
YungsExtras-1.19.2-Fabric-3.1.0.jar
Zoomify-2.9.0.jar
_bclib_deactivated
3dskinlayers-fabric-1.5.2-mc1.19.1.jar
advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar
advdebug-2.3.0.jar

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment] 2023-03-27 03:13
Duplicate of #367 

Somehow the Pehkui versions you have on the client and server are not the same version. Possibly when you added it back to the server a different version got added instead? Double check that you have the exact same version on both the server and client. Might need to contact the hosting site if you're using one of those.

**Closed as not planned by Virtuoel** 2023-03-27 03:13 UTC
Labels: bug
