### ISSUE TITLE
[Bug]: Clouds look separated when the player is small 

### ISSUE THREAD

**Issue by ImSpaceLover** [Virtuoel/Pehkui#179] opened 2021-08-19 20:04 UTC
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

Fabric loader - 0.11.6

### Fabric API version

0.37.2

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Normal
![image](https://user-images.githubusercontent.com/64267797/130136018-254cb78d-a509-4735-951a-448cbdc6a833.png)
1/16 scale
![image](https://user-images.githubusercontent.com/64267797/130135971-96bf5df0-8316-46f9-939c-4fa370eca4bf.png)

### Full list of installed mods

fabric-api-0.37.2+1.17
Pehkui-2.3.0+1.14.4-1.17.1

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment] 2021-10-24 10:47
Duplicate of #125

**Closed as completed** 2021-10-24 10:48 UTC
Labels: bug
