### ISSUE TITLE
immersive portals issue

### ISSUE THREAD

**Issue by phantomblitz** [Virtuoel/Pehkui#89] opened 2021-04-27 06:38 UTC
when i use the 1.16.5 forge version with the immersive portals mod it doesnt resize the character

**Comment by ImSpaceLover** [comment] 2021-04-27 11:15
It's because Immersive Portals' developer didn't add compatibility to the forge version of Pehkui

**Comment by Virtuoel** [comment] 2021-04-28 23:51
Duplicate of https://github.com/qouteall/ImmersivePortalsModForForge/issues/243

**Closed as completed by Virtuoel** 2021-04-28 23:51 UTC
