### ISSUE TITLE
[Bug]: Crash on start

### ISSUE THREAD

**Issue by DenilsonNM** [Virtuoel/Pehkui#361] opened 2023-01-11 18:05 UTC
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

1.16.5-forge-36.2.39

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

just download the latest Pehkui 3.6.3 update (and try with 3.6.2 too) for 1.16.5 for the first time and start the game, when trying to load the mods the game crashes (without the mod the game is fine).
I must say that I tried to use the mod "VMH - Variable Mob Height by Rikurobb" that has Pehkui as a dependency.

the game does not generate a crash report, but I do have the log file that have similar text:

- Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

- Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector pehkui$tickCramming$getBoundingBox(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/util/math/AxisAlignedBB; in pehkui.mixins.json:LivingEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json

I put the full log file later 

### Full list of installed mods and their version numbers

saturn-mc1.16.5-0.0.3.jar, 
repurposed_structures_forge-3.4.7+1.16.5.jar, 
morevillagers-FORGE-1.16.5-1.5.5.jar, 
swingthroughgrass-1.16.4-1.5.3.jar
, flesh2leather-1.0.2.jar, 
ToolBelt-1.16.5-1.16.3.jar, 
ShoulderSurfing-Forge-1.16.5-2.2.17.jar,
 jei-1.16.5-7.7.1.153.jar, 
astikorcarts-1.16.5-1.1.1.jar,
 caelus-forge-1.16.5-2.1.3.2.jar, 
Craftable+Saddles+[1.16.4]-1.3.jar,
 colytra-forge-1.16.5-5.1.1.2.jar,
 Waystones_1.16.5-7.6.4.jar, 
gravestone-1.16.5-1.0.7.jar, 
FastSuite-1.16.4-1.1.1.jar, 
Clumps-6.0.0.28.jar, 
shutupexperimentalsettings-1.0.3.jar, 
FastWorkbench-1.16.5-4.6.1.jar, 
screenscale-1.4.jar, 
Placebo-1.16.5-4.7.0.jar, 
jumpoverfences-1.16.4-1.0.1.jar, 
comforts-forge-1.16.5-4.0.1.5.jar, 
AutoRegLib-1.6-49.jar, 
Trini's+Easier+Netherite+Mod+V1+1.16.4.jar, 
NaturesCompass-1.16.5-1.9.1-forge.jar, 
performant-1.16.2-5-3.99m.jar, 
configured-1.5.2-1.16.5.jar, 
entityculling-forge-mc1.16.5-1.5.2.jar,
 BetterThirdPerson-Forge-1.16.4-1.9.0.jar, 
BasicNetherOres-1.16.5-5.5.0.jar, 
Netherite+Scrap+From+Piglin+Brutes+1.16.5+-+1.0.jar, 
InventoryHud_[1.16.2-1.16.5].forge-3.4.1.jar, 
upgradedcore-1.16.5-1.0.0.3-release.jar,
 FastFurnace-1.16.5-4.5.0.jar, 
ForgivingVoid_1.16.5-5.2.1.jar, 
ferritecore-2.1.1-forge.jar, 
shulkerbox-1.16.5-1.0.3.jar, 
Uncrafter-1.16.5-1.1.0.jar, 
forge-1.16.5-36.2.39-universal.jar, 
Quark-r2.4-322.jar, 
PortableCraftingTable-1.16.5-1.1.0.jar,
 FastLeafDecay-v25.2.jar, 
Disenchanting-forge-1.16.5-1.7.2.jar, 
upgradednetherite-1.16.5-2.0.0.8-release.jar, 
balancedenchanting-1.16.2-1.1.jar,
 xptome-1.16.5-v2.1.5.jar, 
Repurposed_Structures-More_Villagers_Forge_v2.zip, 
EatEggs_1.16.5-1.2.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
[11:39:43] [main/INFO]: ModLauncher running: args [--username, DE4THR4SH, --version, 1.16.5-forge-36.2.39, --gameDir, C:\Users\Denilson\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Denilson\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, dac90c369e9a4bdb843024dde5060d3c, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 925, --height, 530, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[11:39:43] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_281 by Oracle Corporation
[11:39:43] [main/INFO]: OptiFineTransformationService.onLoad
[11:39:43] [main/INFO]: OptiFine ZIP file: C:\Users\Denilson\AppData\Roaming\.minecraft\mods\OptiFine_1.16.5_HD_U_G8.jar
[11:39:43] [main/INFO]: Target.PRE_CLASS is available
[11:39:44] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[11:39:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Denilson/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[11:39:44] [main/INFO]: OptiFineTransformationService.initialize
[11:39:47] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[11:39:47] [main/INFO]: OptiFineTransformationService.transformers
[11:39:47] [main/INFO]: Targets: 311
[11:39:48] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[11:39:49] [main/INFO]: Successfully loaded Mixin Connector [de.maxhenkel.shulkerbox.MixinConnector]
[11:39:49] [main/INFO]: Successfully loaded Mixin Connector [com.performant.coremod.mixin.Connector]
[11:39:49] [main/INFO]: Launching target 'fmlclient' with arguments [--version, 1.16.5-forge-36.2.39, --gameDir, C:\Users\Denilson\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Denilson\AppData\Roaming\.minecraft\assets, --uuid, dac90c369e9a4bdb843024dde5060d3c, --username, DE4THR4SH, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 925, --height, 530]
[11:39:49] [main/WARN]: Reference map 'screenscale.refmap.json' for screenscale.mixins.json could not be read. If this is a development environment you can ignore this message
[11:39:49] [main/INFO]: Performant configs loaded
[11:39:51] [main/INFO]: Patching LivingEntity#attackEntityFrom
[11:39:52] [main/WARN]: Error loading class: net/minecraft/block/entity/LecternBlockEntity$1 (java.lang.ClassNotFoundException: null)
[11:39:52] [main/WARN]: @Mixin target net.minecraft.block.entity.LecternBlockEntity$1 was not found pehkui.mixins.json:reach.LecternBlockEntityMixin
[11:39:52] [main/INFO]: Patching DataPackRegistries#<init>
[11:39:53] [main/INFO]: Patching ItemStack#onItemUse
[11:39:53] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.forge.BasicEventHooksMixin as config disables it.
[11:39:53] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.world.WorldMixin as config disables it.
[11:39:53] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.entity.LivingEntityUpdateEventMixin as config disables it.
[11:39:53] [main/INFO]: Disabling farm leak reporting due to incompat with pekhui
[11:39:53] [main/INFO]: Disabling dynamic entity rendering as entity culling is present
[11:39:53] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.entity.EntityFPSMixin as config disables it.
[11:39:53] [main/INFO]: Disabling dynamic entity rendering as entity culling is present
[11:39:53] [main/INFO]: Not enabling mixin forcom.performant.coremod.mixin.entity.EntityRendererFPSMixin as config disables it.
[11:39:55] [main/INFO]: Patching BlockModelShapes#getModelLocation
[11:39:55] [main/INFO]: Patching LivingEntity#attackEntityFrom
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[11:39:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:282)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	... 10 more
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector pehkui$tickCramming$getBoundingBox(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/util/math/AxisAlignedBB; in pehkui.mixins.json:LivingEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[11:39:56] [main/INFO]: [java.lang.Throwable:printStackTrace:668]: 	... 35 more

**Comment by DenilsonNM** [comment] 2023-01-11 18:15
After read the log, I see that performant mod has errors with pehkui

**Comment by Virtuoel** [comment] 2023-02-23 19:13
Duplicate of https://github.com/Virtuoel/Pehkui/issues/354

Looks to be caused by Performant completely `@Overwrite`-ing the `pushEntities`/`func_85033_bc` method. Pehkui tries to modify part of it for hitbox adjustments, but then cannot as Performant moved certain contents to another method.

If this issue still occurs with the newest version of Performant, report to Performant's issue tracker instead.

**Closed as not planned by Virtuoel** 2023-02-23 19:13 UTC
Labels: bug
