### ISSUE TITLE
[Bug]: Crash in my modpack

### ISSUE THREAD

**Issue by Meidde** [Virtuoel/Pehkui#440] opened 2023-08-07 13:38 UTC
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

Forge Loader 36.2.39

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Hi i need your mod in my Modpack for to have the benefits of it, but minecraft loads and closes, and generates this error in the Logs

[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/849669310.call(Unknown Source)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[10:16:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$764/1957360925.get(Unknown Source)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$772/1718940023.accept(Unknown Source)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$708/1719949466.run(Unknown Source)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[10:16:02] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector pehkui$tickCramming$getBoundingBox(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/util/math/AxisAlignedBB; in pehkui.mixins.json:LivingEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[10:16:02] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 28 more

### Full list of installed mods and their version numbers

	Mod List: 
Patchouli
Pehkui
CreRaces
Saturn               
Not Enough Crashes         
Hit Indication             
Connectivity Mod           
PortableCraft             
YUNG's Better Caves         
TerraForged                  
Xaero's World Map          
ConnectedTexturesMod        
Placebo                  
Citadel                   
YUNG's API                   
Enhanced Mob Spawners       
Item Zoom                  
LootBeams                 
Anti Mob Farm                
Pick Up Notifier      
FPS Reducer                
Chat Heads                
Supplementaries        
Emojiful            
Konkrete                      
Auto Third Person         
Simple Ores               
Equipment Compare         
Out of Sight             
Torchmaster                   
Crash Utilities               
AI Reducer                    
Ping                          
Simple Shops                  
Blur                          
SimpleCoreLib                
ModularVoiceChat                     
Divine Missions               
Highlighter                
Cluttered        
Many Ideas Core     
Touhou Little Maid      
Hole Filler Mod         
Curios API                   
Never Enough Currency        
Item Blacklist              
In-Game Account Switcher    
Collective             
Better Biome Blend           
Multiversum of RPG Weapons 
Joy of Painting          
Dungeons of Exile           
Dawn Of Time : Builder Edition
ChatImg                    
Custom NPCs                  
WorldEdit               
Starter Kit              
Inventory Profiles Next  
Architectury          
Spoiled              
Global XP    
Chimes              
Cloth Config v4 API    
Small Ships Mod         
Player Trade Mod         
FastLeafDecay         
GeckoLib            
Better Mods Button       
Neko’s Enchanted Books     
Corail Pillar        
ConquestRecipes  
Borderless Window      
Anti Bonemeal             
Stylish Effects         
Notes                     
Hand Over Your Items     
Serene Shrubbery        
Mermaid Tail Mod     
Comics Bubbles Chat   
Basic End Ores         
RPG-Hud                  
Mine and Slash       
XL Packets             
Just Enough Items   
EF_weapon_extanded     
Passable Foliage     
Harder Branch Mining Mod   
FastSuite             
Clumps                 
Serene Seasons           
Hidden Names           
Item Borders                 
Basic Nether Ores            
Champions                   
Epic Knights Mod           
Better Animals Plus           
LazyDFU                
Starlight            
Sulfuric              
ConquestReforged            
Additional Lights          
Ice and Fire       
Farsight mod                
Wall-Jump!                
JEI Tweaker             
iChunUtil                
Memory Leak Fix     
CraftTweaker            
KeepCuriosInventory          
Subterranean Wilderness  
Console Experience         
TellMe                
Smoothchunk mod    
BiggerChatHistory  
libIPN                   
Mouse Tweaks            
Behgameon               
Jade                       
Shoulder Surfing         
Yamato moveset             
Smooth Boot             
Swashbucklers            
Recipes Library         
Iceberg               
Xaero's Minimap         
More Player Models   
Polymorph           
Krypton Reforged          
Keyboard Wizard          
ParCool!             
Performant              
EntityCulling            
Hardcore Revival           
Armourer's Workshop        
Many Ideas Doors           
No Recipe Advancements      
Library Of Exile          
FancyMenu              
AppleSkin      
Lootr                     
Ferrite Core                  
Custom Cursor Mod             
EpicAddon SwordTrail Module 
Epic Fight                    
Back Tools              
Puzzles Lib           
BetterF3            
Packet Fixer (Forge)      
XK's Deco                
CosmeticArmorReworked      
Sound Filters          
Overloaded Armor Bar   
DEUF - Duplicate Entity UUID 
Presence Footsteps           
Default Options               

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Chudwig** [comment] 2023-08-09 21:46
I experience the same crash, happens in the Forge Mod Loader "early loading progress" stage. I have (roughly) the same mods as Meidde, including the same debug log.
1.16.5 - Forge 36.2.39

Im going to test and play around with it - I'll let you know what happens!

**Comment by Chudwig** [comment] 2023-08-09 22:08
Seems to be an issue with **Performant**.
Version: 1.16.5
Loader: Forge 36.2.39
Mods Loaded:
Performant
Pehkui
Not Enough Crashes (Forge)
Origins (Forge)

Result:
[09Aug2023 18:05:51.089] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$pehkui$tickMovement$minVelocity$0(I)Z to md3a6398$lambda$pehkui$tickMovement$minVelocity$0$1 in pehkui.mixins.json:LivingEntityMixin
[09Aug2023 18:05:51.095] [pool-3-thread-1/DEBUG] [mixin/]: Mixing compat116minus.LivingEntityMixin from pehkui.mixins.json into net.minecraft.entity.LivingEntity
[09Aug2023 18:05:51.096] [pool-3-thread-1/DEBUG] [mixin/]: Mixing compat116plus.compat1193minus.LivingEntityMixin from pehkui.mixins.json into net.minecraft.entity.LivingEntity
[09Aug2023 18:05:51.096] [pool-3-thread-1/DEBUG] [mixin/]: Mixing LivingEntityMixin from caelus.mixins.json into net.minecraft.entity.LivingEntity
[09Aug2023 18:05:51.097] [pool-3-thread-1/DEBUG] [mixin/]: Mixing LivingEntityMixin from origins.mixins.json into net.minecraft.entity.LivingEntity
[09Aug2023 18:05:51.098] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$preventDeath$6(Lnet/minecraft/util/DamageSource;Lio/github/apace100/origins/power/PreventDeathPower;)Z to md3a6398$lambda$preventDeath$6$2 in origins.mixins.json:LivingEntityMixin
[09Aug2023 18:05:51.099] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$invokeKillAction$5(Lnet/minecraft/util/DamageSource;FLio/github/apace100/origins/power/SelfActionOnKillPower;)V to md3a6398$lambda$invokeKillAction$5$3 in origins.mixins.json:LivingEntityMixin
[09Aug2023 18:05:51.100] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$invokeHitActions$4(Lnet/minecraft/util/DamageSource;FLio/github/apace100/origins/power/TargetActionOnHitPower;)V to md3a6398$lambda$invokeHitActions$4$4 in origins.mixins.json:LivingEntityMixin
[09Aug2023 18:05:51.101] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$invokeHitActions$3(Lnet/minecraft/util/DamageSource;FLio/github/apace100/origins/power/SelfActionOnHitPower;)V to md3a6398$lambda$invokeHitActions$3$5 in origins.mixins.json:LivingEntityMixin
[09Aug2023 18:05:51.101] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$invokeHitActions$2(Lnet/minecraft/util/DamageSource;FLio/github/apace100/origins/power/AttackerActionWhenHitPower;)V to md3a6398$lambda$invokeHitActions$2$6 in origins.mixins.json:LivingEntityMixin
[09Aug2023 18:05:51.106] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$invokeHitActions$1(Lnet/minecraft/util/DamageSource;FLio/github/apace100/origins/power/SelfActionWhenHitPower;)V to md3a6398$lambda$invokeHitActions$1$7 in origins.mixins.json:LivingEntityMixin
[09Aug2023 18:05:51.108] [pool-3-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$modifyWalkableFluids$0(Lnet/minecraft/fluid/Fluid;Lio/github/apace100/origins/power/WalkOnFluidPower;)Z to md3a6398$lambda$modifyWalkableFluids$0$8 in origins.mixins.json:LivingEntityMixin
[09Aug2023 18:05:51.124] [pool-3-thread-1/DEBUG] [mixin/]: Mixing LivingEntityMixin from origins.forge.mixins.json into net.minecraft.entity.LivingEntity
[09Aug2023 18:05:51.126] [pool-3-thread-1/DEBUG] [mixin/]: Mixing compat115plus.LivingEntityMixin from pehkui.mixins.json into net.minecraft.entity.LivingEntity
[09Aug2023 18:05:51.126] [pool-3-thread-1/DEBUG] [mixin/]: Mixing compat115plus.compat116minus.LivingEntityMixin from pehkui.mixins.json into net.minecraft.entity.LivingEntity
[09Aug2023 18:05:51.668] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[09Aug2023 18:05:51.668] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[09Aug2023 18:05:51.668] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[09Aug2023 18:05:51.668] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[09Aug2023 18:05:51.669] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[09Aug2023 18:05:51.671] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[09Aug2023 18:05:51.671] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[09Aug2023 18:05:51.671] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09Aug2023 18:05:51.672] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09Aug2023 18:05:51.672] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09Aug2023 18:05:51.673] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[09Aug2023 18:05:51.673] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[09Aug2023 18:05:51.673] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$501/1582277082.call(Unknown Source)
[09Aug2023 18:05:51.673] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[09Aug2023 18:05:51.674] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[09Aug2023 18:05:51.674] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[09Aug2023 18:05:51.674] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[09Aug2023 18:05:51.674] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[09Aug2023 18:05:51.674] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[09Aug2023 18:05:51.675] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[09Aug2023 18:05:51.675] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[09Aug2023 18:05:51.675] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[09Aug2023 18:05:51.675] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[09Aug2023 18:05:51.676] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[09Aug2023 18:05:51.676] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[09Aug2023 18:05:51.676] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[09Aug2023 18:05:51.676] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[09Aug2023 18:05:51.677] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[09Aug2023 18:05:51.677] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[09Aug2023 18:05:51.677] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[09Aug2023 18:05:51.677] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09Aug2023 18:05:51.677] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)
[09Aug2023 18:05:51.677] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[09Aug2023 18:05:51.677] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[09Aug2023 18:05:51.678] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[09Aug2023 18:05:51.678] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$726/1797324198.get(Unknown Source)
[09Aug2023 18:05:51.678] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[09Aug2023 18:05:51.678] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$734/1504030294.accept(Unknown Source)
[09Aug2023 18:05:51.678] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[09Aug2023 18:05:51.678] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[09Aug2023 18:05:51.678] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[09Aug2023 18:05:51.678] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[09Aug2023 18:05:51.679] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[09Aug2023 18:05:51.679] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$675/1185188034.run(Unknown Source)
[09Aug2023 18:05:51.679] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09Aug2023 18:05:51.679] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09Aug2023 18:05:51.679] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[09Aug2023 18:05:51.679] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[09Aug2023 18:05:51.679] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)
[09Aug2023 18:05:51.680] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector pehkui$tickCramming$getBoundingBox(Lnet/minecraft/entity/LivingEntity;)Lnet/minecraft/util/math/AxisAlignedBB; in pehkui.mixins.json:LivingEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json
[09Aug2023 18:05:51.680] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[09Aug2023 18:05:51.680] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[09Aug2023 18:05:51.680] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[09Aug2023 18:05:51.680] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[09Aug2023 18:05:51.680] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[09Aug2023 18:05:51.680] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[09Aug2023 18:05:51.680] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[09Aug2023 18:05:51.681] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[09Aug2023 18:05:51.681] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 28 more

**Comment by Virtuoel** [comment] 2023-08-09 22:24
Ah, Performant again. Looks like this is a duplicate of #354 and a duplicate of https://github.com/someaddons/performant_issues/issues/267. Would probably be useful to add your log to Performant's issue.

**Closed as not planned by Virtuoel** 2023-08-09 22:24 UTC
Labels: bug
