### ISSUE TITLE
Pehkuiconflict rpgz

### ISSUE THREAD

**Issue by zc1108aaa** [Virtuoel/Pehkui#519] opened 2024-05-31 06:38 UTC
### Minecraft version(s)

1.20.1

### Minecraft version details

1

### Mod loader

Fabric

### Mod loader version

0.15.11

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

1

### Full list of installed mods and their version numbers

1

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

](https://github.com/MehVahdJukaar/Randomium/issues/34)

**Comment by Virtuoel** [comment] 2024-05-31 09:01
Duplicate of #482

This incompatibility was already fixed on RpgZ's end (https://github.com/Globox1997/RpgZ/pull/43), but it seems they haven't released a 1.20.1 version with that fix yet for whatever reason.

**Closed as not planned by Virtuoel** 2024-05-31 09:01 UTC
Labels: bug, duplicate
