### ISSUE TITLE
[Suggestion]: Pick Up Players,Squash Players,Carry Players

### ISSUE THREAD

**Issue by GiantessElsie** [Virtuoel/Pehkui#442] opened 2023-08-11 09:21 UTC
### What is your suggestion?

This would be a good feature if u can make pehkui that if u are bigger then the entity u can pick it up and maybe throw it or carrying it and another if u are big and a player is small u can walk on it and the player that is small gets damage by the big player

**Comment by Virtuoel** [comment] 2023-08-22 15:18
Partial duplicate of #183. Unfortunately this is out of scope for Pehkui itself. Though it would be interesting to see some sort of Pehkui addon mod that does this.

**Closed as not planned by Virtuoel** 2023-08-22 15:18 UTC
Labels: enhancement

**Comment by GiantessElsie** [comment] 2023-08-22 15:24
@Virtuoel There is a mod that can do it but it is out of date it doesn't support 1.20.1 but u can maybe use the code to implement it into pehkui
https://www.curseforge.com/minecraft/mc-mods/gargantuan
