### ISSUE TITLE
[Bug]: Scaled players rubber banding with Performant

### ISSUE THREAD

**Issue by LunafeyLazuli** [Virtuoel/Pehkui#321] opened 2022-09-09 13:44 UTC
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

Forge 36.2.39

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

When you have Performant installed with Pehkui, a lot of rubber banding happens when you are a smaller size. For more context, on my server, I run CreRaces which uses Pehkui to make some of the races like Pixies and Fairies smaller. If you have performant installed on the server, then a TON of rubber banding starts happening when you try to use the wings mods to fly around, or in creative flight with "moved wrongly" being spammed in the console. With some testing done, it definitely is Performant+Pehkui, the theory is that they both touch how movement is done through both mods and kind of end up fighting up a bit, but I'm not a mod maker again, just a theory. xD

### Full list of installed mods and their version numbers

AI-Improvements-1.16.5-0.5.0.jar
AdvancementPlaques-1.16.5-1.4.1.jar
AgeingSpawners-1.16.5-1.1.0.jar
Alex's Delight 1.1.3 - Forge 1.16.5.jar
Aquaculture-1.16.5-2.1.22.jar
Artifacts-1.16.5-2.10.5.jar
AttributeFix-1.16.5-10.1.4.jar
Atum-1.16.5-2.2.11.jar
AutoRegLib-1.6-49.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterDungeons-1.16.4-1.2.1.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterPortals-1.16.4-0.3.9.jar
BetterThanMending-1.6.0.jar
BiomesOPlenty-1.16.5-13.1.0.488-universal.jar
BlackAuresPaintings_1.0_Forge_1.16.5.jar
Bookshelf-Forge-1.16.5-10.4.32.jar
Botania-1.16.5-420.2.jar
BotanyPots-1.16.5-7.1.39.jar
CNB-1.16.3_5-1.2.11.jar
CavesCliffsBackportAdditions-3.4.jar
Chimes-1.0.0-1.16.5.jar
Clumps-6.0.0.28.jar
Compat-O-Plenty-1.16.5-1.0.7.jar
Compressium-1.16.5-1.2.3.jar
Controlling-7.0.0.28.jar
CosmeticArmorReworked-1.16.5-v5.jar
CraftTweaker-1.16.5-7.1.2.511.jar
CraftingTweaks_1.16.5-12.2.1.jar
CustomNPCs-1.16.5.20220515.jar
DoggyTalents-1.16.5-2.1.15.jar
DramaticDoors-1.16.5-1.5.0.jar
DungeonsArise-1.16.5-2.1.49-beta.jar
DynamicSurroundings-1.16.5-4.0.5.0.jar
EasierSleeping-1.16.5-2.0.0.jar
EnderMail-1.16.5-1.2.2.jar
FarmersDelight-1.16.5-0.6.0.jar
FarmingForBlockheads_1.16.5-7.3.1.jar
Feywild-1.16.5-2.1.3.jar
Goblins_Dungeons_1.0.6-1.16.jar
GottschCore-mc1.16.5-f36.2.34-v1.6.0.jar
Hats-1.16.5-10.3.3.jar
Iceberg-1.16.5-1.0.45.jar
ImprovedBackpacks-1.6.2.1.jar
Inspirations-1.16.5-1.2.3.38.jar
IronAgeFurniture-1.16.3-1.16.5-0.2.0.15.jar
JAVD-2.6.1-build.48+mc1.16.5.jar
JEITweaker-1.16.5-1.1.0.49.jar
Jade-1.16.4-2.8.3.jar
KleeSlabs_1.16.5-9.2.1.jar
LibX-1.16.3-1.0.76.jar
Mantle-1.16.5-1.6.157.jar
MouseTweaks-2.14-mc1.16.2.jar
MythicBotany-1.16.5-1.4.19.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
Neat 1.7-27.jar
NefsMedievalPub+v1.0(1.16.5).jar
NetherPortalFix_1.16.3-7.2.1.jar
NyfsQuiver-1.16.5-0.6.3.jar
Orcz 0.67 1.16.5.jar
Paraglider-1.16.5-1.3.2.10.jar
PassableFoliage-1.16.5-2.4.0.jar
Patchouli-1.16.4-53.3.jar
Pehkui-3.4.2+1.16.5-forge.jar
Placebo-1.16.5-4.7.0.jar
Prism-1.16.5-1.0.1.jar
Project_MMO-1.16.5-3.67.6.jar
Quark-r2.4-322.jar
QuarkOddities-1.16.3.jar
QuestPlaques-1.16.5-1.0.2.jar
SereneSeasons-1.16.5-4.0.1.126-universal.jar
ServerTabInfo-1.16.4-1.3.4.jar
SkyVillage_1.0.0_1.16.5.jar
SoL-Carrot-1.16.5-1.10.1.jar
SpartanShields-1.16.5-2.1.2.jar
StorageDrawers-1.16.3-8.5.2.jar
TanHugeTrees-1.16.5-2.0.4.jar
TerraForged-1.16.5-0.2.16-BETA-2.jar
ToastControl-1.16.5-4.4.0.jar
TreeChop-1.16.4-0.14.6-fixed.jar
UnionLib-1.16.5-3.3.7.jar
UnusualEnd1.16_V1.1.7.jar
Waystones_1.16.5-7.6.4.jar
Wyrmroost-1.16.3-1.2.11.jar
YungsApi-1.16.4-Forge-13.jar
YungsExtras-Forge-1.16.4-1.0.jar
abnormals_core-1.16.5-3.3.1.jar
absentbydesign-1.16.5-1.5.2.jar
additional_lights-1.16.4-2.1.3.jar
alexsmobs-1.12.1.jar
appleskin-forge-mc1.16.x-2.4.0.jar
architectury-1.32.66.jar
ars_elemental-1.16.5-0.1.6.3.jar
ars_nouveau-1.16.5-1.25.7.jar
arsarsenal-1.1.0-1.16.5.jar
atmospheric-1.16.5-3.1.1.jar
backpacked-2.1.8-1.16.5.jar
betterendforge-1.16.5-1.6.3.jar
betternether_reforged-1.2.jar
bettervillage-forge-1.16.5-2.0.0.jar
bloodandgore-1.16.5-v1.1.jar
brewevolution0.2.1.jar
bygonenether-1.2.1-1.16.5.jar
caelus-forge-1.16.5-2.1.3.2.jar
cavebiomeapi-1.16.5-1.4.2.jar
cavesandcliffs-1.16.5-7.2.0.jar
chipped-1.16.5-1.2.1-forge.jar
chocolate-1.3.0-1.16.4.jar
citadel-1.8.1-1.16.5.jar
cloth-config-4.16.91-forge.jar
collective-1.16.5-4.52.jar
comforts-forge-1.16.5-4.0.1.5.jar
connectivity-2.4-1.16.5.jar
constructionwand-1.16.5-2.6.jar
creraces-1.16.5-b1.5.6_02.jar
culturaldelights-1.16.5-0.9.2.jar
curios-forge-1.16.5-4.0.8.2.jar
dcintegration-forge-2.4.7-1.16.jar
decorative_blocks-1.16.4-1.7.2.jar
diamethyst_arrows-0.1.0-1.16.5.jar
diamethysts-0.1.1-1.16.5.jar
dicemcpmmonbt-1.16-1.2.2.jar
dragonfight-1.7.jar
drawerfps-2.1.jar
dreadsteel-1.16.5-1.1.1.jar
drinkbeer-1.16.5-2.3.5.jar
dynviewdist-2.0.jar
eidolon-0.2.7.jar
endrem-5.0.3-R-1.16.5.jar
ends_delight-1.16.5-1.5.jar
enhancedcelestials-2.0.9-1.16.5.jar
environmental-1.16.5-1.1.1.jar
expandability-2.0.1-forge.jar
extcaves-2.4.jar
farmersdelightintegrations-1.16.5-1.2.jar
farmersrespite-1.16.5-1.1.jar
farsight-1.7.jar
ferritecore-2.1.0-forge.jar
ftb-chunks-forge-1605.3.2-build.115.jar
ftb-essentials-1605.1.5-build.32.jar
ftb-library-forge-1605.3.4-build.90.jar
ftb-quests-forge-1605.3.6-build.98.jar
ftb-ranks-forge-1605.1.6-build.33.jar
ftb-teams-forge-1605.2.3-build.40.jar
geckolib-forge-1.16.5-3.0.89.jar
geckolib-forge-1.16.5-3.0.90.jar
greekfantasy-16.5.5.jar
hats
hexerei-0.1.4.jar
iChunUtil-1.16.5-10.6.1.jar
iceandfire-2.1.11-1.16.5.jar
immersivecooking-1.2.0.jar
item-filters-forge-1605.2.5-build.9.jar
jei-1.16.5-7.7.1.152.jar
jmi-1.16.5-0.8.1-47.jar
journeymap-1.16.5-5.8.5p5.jar
konkrete_forge_1.5.0_MC_1.16.2-1.16.5.jar
lanterncolors-1.16.3-2.1.1.jar
largemeals-1.16.5-2.2.jar
lazydfu-0.1.3.jar
libraryferret-forge-1.16.5-3.0.0.jar
lightmanscurrency-1.16.4-1.0.5.6a.jar
macawsbridgesbop-1.16.5-1.4.jar
macawsroofsbop-1.16.5-1.2.jar
mana-and-artifice-1.5.1.7.jar
mcw-bridges-2.0.3-mc1.16.5.jar
mcw-doors-1.0.7-mc1.16.5.jar
mcw-fences-1.0.6-mc1.16.5.jar
mcw-furniture-3.0.1-mc1.16.5.jar
mcw-paintings-1.0.4-mc1.16.5.jar
mcw-paths-1.0.1-mc1.16.5.jar
mcw-roofs-2.1.2-mc1.16.5.jar
mcw-trapdoors-1.0.7-mc1.16.5.jar
mcw-windows-2.0.3-mc1.16.5.jar
mcwfencesbop-1.16.5-1.3.jar
mdecore-1.16.4-16.1.0.jar
mermaidtail-1.4b.jar
mgui-1.16.5-3.3.0.jar
mmlib-1.1.1-1.16.5.jar
moredragoneggs-2.5.jar
morestoragedrawers-1.16.5-1.1.2.jar
morevanillalib-1.16.4-1.4.1.jar
nethers_delight-2.1.jar
observerlib-1.16.5-1.5.3.jar
pamhc2crops-1.16.3-1.0.2.jar
pamhc2foodcore-1.16.3-1.0.2.jar
pamhc2foodextended-1.16.3-1.0.4.jar
pamhc2trees-1.16.3-1.0.1.jar
performant-1.16.2-5-3.99m.jar
pmmobridge-1.16.5-1.0.7.jar
polymorph-forge-1.16.5-0.40.jar
projectvibrantjourneys-1.16.5-3.2.11.jar
questsadditions-1.16-1.4.0.jar
rpggods-16.5.4.jar
selene-1.16.5-1.9.0.jar
shetiphiancore-1.16-3.8.15.jar
skinned_lanterns-1.16.5-1.3.1.jar
smallships-1.16.5-1.10.1.jar
snowundertrees-1.16.5-v1.3.jar
spark-1.9.1-forge.jar
spiders-2.0-1.16.4-1.0.4.jar
storage_overhaul-1.16.5-1.0.4.jar
subwild-1.3.1.jar
supplementaries-1.16.5-0.18.4b.jar
swingthroughgrass-1.16.4-1.5.3.jar
table_top_craft-1.16-1.2.0.jar
terraqueous-1.16-1.7.25.jar
tetra-1.16.5-3.20.0.jar
tetranomicon-1.3.jar
tetrapak-1.16.5-0.3.4.jar
tombstone-6.7.9-1.16.5.jar
toms_storage-1.2.19.jar
toofast-1.16.5-0.0.0.1.jar
totw_additions-1.1.0.jar
towers_of_the_wild-1.16.3-2.1.0.1.jar
vanillahammers-1.16.4-2.2.0.jar
wings-2.1.0-1.16.5.jar
worldedit-mod-7.2.5-dist.jar

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment] 2022-09-09 15:06
Not really fixable on Pehkui's end. Performant does quite a few changes to entity movement last I checked.
Duplicate of https://github.com/someaddons/performant_issues/issues/255

**Closed as not planned by Virtuoel** 2022-09-09 15:06 UTC
Labels: bug

**Comment by LunafeyLazuli** [comment] 2022-09-09 18:55
Yeah, we tried to see which end it was on since we haven't gotten a response from Performant yet, so figured I'd try it here too XD
