### ISSUE TITLE
well size is not working  in forge

### ISSUE THREAD

**Issue by xxxprosoldierxxx** [Virtuoel/Pehkui#144] opened 2021-07-24 15:59 UTC
well when i was testing size it was not working for som resone i cant be big or small on this mod'
srsly why

**Comment by Virtuoel** [comment] 2021-07-24 16:05
What Pehkui version were you using and what other mods do you have installed?

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:22
yes i install it pehkui

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:23
also i haw ohers mods

**Comment by Virtuoel** [comment] 2021-07-24 16:29
> also i haw ohers mods

Yes, but what are those mods? Please provide your mod list (including the mod version numbers).

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:30
1.16.5

**Comment by Virtuoel** [comment] 2021-07-24 16:32
That's the Minecraft version, not the version of your mods. What I am asking is, can you give the names of all the files that are in your `mods` folder?

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:32
hold on

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:32
am i suports send my mods?

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:34
oh i get it u mean the verison of mods

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:36
well its

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:38
just give me time

**Comment by Virtuoel** [comment] 2021-07-24 16:39
I suppose a screenshot of your mods folder would work too.

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:40
oh ok
let me try this

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:47
![20210724_184354](https://user-images.githubusercontent.com/87656180/126875417-43e1e0d7-19bf-49fd-a892-113ebd9b6c56.jpg) 
u mean like this

**Comment by Virtuoel** [comment] 2021-07-24 16:50
When you mentioned you were `testing size`, how were you testing it? Were you using Immersive Portals' portals to change your size, or some other way?

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:54
well i was testing if i can make my self small by building 3x3 and 5x5 portal  but dint work even mobs entity and others

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:56
like this when i was trying test size
![2021-07-24_18 56 00](https://user-images.githubusercontent.com/87656180/126875682-1e30fdfc-6d97-492a-8986-a1b5de5e0de7.png)

**Comment by Virtuoel** [comment] 2021-07-24 16:57
Unfortunately the Forge version of Immersive Portals doesn't support resizing with Pehkui yet. Have to wait for them to update, whenever that may be.

Duplicate of qouteall/ImmersivePortalsModForForge#243

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 16:57
oh thx for asking this

**Closed as completed by Virtuoel** 2021-07-24 16:57 UTC

**Comment by xxxprosoldierxxx** [comment] 2021-07-24 17:01
also i forgot i dont haw frabic on this game
