### ISSUE TITLE
[Bug]: Game crashes on start up

### ISSUE THREAD

**Issue by willboyz92nd** [Virtuoel/Pehkui#270] opened 2022-05-04 14:25 UTC
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

Forge version 40.1.14

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Game crashes on startup and does not produce an error log

### Full list of installed mods

Pehkui
AppleSkin
Caelus
JourneyMap
JEI
Mouse Tweaks
Origins
Origins: Classes
Bucolic Origins (dependant on Pehkui but the game crashes without this mod)

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output: There is no crash log it's right on startup but here is the main log -> 08:45:55] [main/INFO]: ModLauncher running: args [--username, Willboyz92nd, --version, forge-40.1.14, --gameDir, C:\Users\Sonic\curseforge\minecraft\Instances\forge testing, --assetsDir, C:\Users\Sonic\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, 7fd7cd78f92a4b808b4a80734f4ffe7d, --accessToken, ????????, --clientId, Yzk2OWU2ZDEtZmJkNi00ZjQzLWFmYjctMGNjN2I1ODllNTBl, --xuid, 2535446110219285, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.14, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[08:45:55] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[08:45:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Sonic/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[08:45:57] [main/INFO]: Found mod file bucolicorigins-3.1[FORGE].jar of type MOD with locator {mods folder locator at C:\Users\Sonic\curseforge\minecraft\Instances\forge testing\mods}
[08:45:57] [main/INFO]: Found mod file caelus-forge-1.18.1-3.0.0.2.jar of type MOD with locator {mods folder locator at C:\Users\Sonic\curseforge\minecraft\Instances\forge testing\mods}
[08:45:57] [main/INFO]: Found mod file Origins-1.18.2-1.4.1.1-unified.jar of type MOD with locator {mods folder locator at C:\Users\Sonic\curseforge\minecraft\Instances\forge testing\mods}
[08:45:57] [main/INFO]: Found mod file origins-classes-forge-1.1.3.jar of type MOD with locator {mods folder locator at C:\Users\Sonic\curseforge\minecraft\Instances\forge testing\mods}
[08:45:57] [main/INFO]: Found mod file Pehkui-3.3.0+1.18.2-forge.jar of type MOD with locator {mods folder locator at C:\Users\Sonic\curseforge\minecraft\Instances\forge testing\mods}
[08:45:58] [main/INFO]: Found mod file fmlcore-1.18.2-40.1.14.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[08:45:58] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.1.14.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[08:45:58] [main/INFO]: Found mod file mclanguage-1.18.2-40.1.14.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[08:45:58] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[08:45:58] [main/INFO]: Found mod file forge-1.18.2-40.1.14-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@3704122f
[08:46:03] [main/INFO]: Compatibility level set to JAVA_17
[08:46:04] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-40.1.14, --gameDir, C:\Users\Sonic\curseforge\minecraft\Instances\forge testing, --assetsDir, C:\Users\Sonic\curseforge\minecraft\Install\assets, --uuid, 7fd7cd78f92a4b808b4a80734f4ffe7d, --username, Willboyz92nd, --assetIndex, 1.18, --accessToken, ????????, --clientId, Yzk2OWU2ZDEtZmJkNi00ZjQzLWFmYjctMGNjN2I1ODllNTBl, --xuid, 2535446110219285, --userType, msa, --versionType, release, --width, 1024, --height, 768]</summary>
<p>

**Comment by Attyelep** [comment] 2022-05-05 18:47
I have the same problem
Using Bucolic origins

**Comment by EdwinMindcraft** [comment] 2022-05-05 22:21
The bug is, as far as I can tell due to the new step height attribute introduced in version 3, reverted in 15 (which works fine) and reintroduced in 16 (which crashes again). As stated above, the logs are extraordinarily unhelpful, but here's the [40.1.16 commit](https://github.com/MinecraftForge/MinecraftForge/commit/abc3353375d7bb084ce88a1865a1e69548c1307a).

This can be reproduced with only Pehkui and forge installed.

**Comment by Attyelep** [comment] 2022-05-06 15:24
Is there a way of fixing this then?
Sorry for trouble, Would Very much like to use it on a server!
Thanks!

**Comment by Virtuoel** [comment] 2022-05-16 08:15
Resolved in Pehkui 3.3.1.

**Closed as completed by Virtuoel** 2022-05-16 08:15 UTC
Labels: bug
