### ISSUE TITLE
[Bug]: Crash Report Version 3.8.3+1.14.4-1.21.jar

### ISSUE THREAD

**Issue by vRetronix** [Virtuoel/Pehkui#539] opened 2024-07-28 03:52 UTC
### Minecraft version(s)

1.20.1

### Mod loader

Fabric

### Mod loader version

0.15.11

### Fabric API version

Fabric API 0.92.2+1.20.1

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

https://mclo.gs/673XZta

### Full list of installed mods and their version numbers

Loading 312 mods:
	- advanced_runtime_resource_pack 0.8.1
	- advancementplaques 1.4.11
	- adventurez 1.4.20
	- alloy_forgery 2.1.2+1.20
	- amplified_nether 1.2.5
	- appleskin 2.5.1+mc1.20
	- archers 1.2.1+1.20.1
	   |-- com_github_zsoltmolnarrr_tinyconfig 2.3.2
	   \-- structure_pool_api 1.0+1.20.1
	- architectury 9.2.14
	- argonauts 1.0.10
	   \-- placeholder-api 2.1.1+1.20
	- artifacts 9.5.12
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- expandability 9.0.4
	   |-- mixinextras 0.3.5
	   \-- step-height-entity-attribute 1.2.0
	- autotag-convention 2.0.2+1.20
	   \-- autotag 2.0.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yungsapi 1.20-Fabric-4.0.5
	   |-- mixinextras 0.3.5
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsextras 1.20-Fabric-4.0.3
	- yungsmenutweaks 1.20.1-Fabric-1.0.2

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

[latest.log](https://github.com/user-attachments/files/16402131/latest.log)

**Comment by Virtuoel** [comment] 2024-07-28 08:35
Duplicate of https://github.com/Virtuoel/Pehkui/issues/482

This incompatibility was already fixed on RpgZ's end (https://github.com/Globox1997/RpgZ/pull/43), but it seems they haven't released a 1.20.1 version with that fix yet for whatever reason.

**Closed as not planned by Virtuoel** 2024-07-28 08:35 UTC
Labels: bug

**Comment by vRetronix** [comment] 2024-07-28 17:27
> Duplicate of #482
> 
> This incompatibility was already fixed on RpgZ's end ([Globox1997/RpgZ#43](https://github.com/Globox1997/RpgZ/pull/43)), but it seems they haven't released a 1.20.1 version with that fix yet for whatever reason.

Ahhh Okay, Its rpgZ Understood. Ill just wait til they fix it to 1.20.1
