### ISSUE TITLE
Pehkui crashing on startup

### ISSUE THREAD

**Issue by saviourom** [Virtuoel/Pehkui#358] opened 2023-01-05 21:33 UTC
Version 1.19.2
[modlist]([Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Farmer's Respite (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Diagonal Fences (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Pick Up Notifier (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[XP Tome (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/xp-tome)
[Easy Anvils (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Default Options (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/default-options)
[Let's do Wine! (by satisfyL)](https://www.curseforge.com/minecraft/mc-mods/lets-do-wine)
[JER Integration (by AlasDiablo)](https://www.curseforge.com/minecraft/mc-mods/jer-integration)
[TexTrue's Rubidium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options)
[Effective (Forge) (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/effective-forge)
[Rebind Narrator (by quat1024)](https://www.curseforge.com/minecraft/mc-mods/rebind-narrator)
[Savage & Ravage (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage)
[Unique Enchantments - Battle (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/unique-enchantments-battle)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Illagers Wear Armor (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor)
[Adorn (Forge) (by Juicebus)](https://www.curseforge.com/minecraft/mc-mods/adorn-for-forge)
[Blue Skies (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/blue-skies)
[Buzzier Bees (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/buzzier-bees)
[Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Bartering Station (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/bartering-station)
[Bygone Nether (by izofar)](https://www.curseforge.com/minecraft/mc-mods/bygone-nether)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[GraveStone Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)
[Unusual End (by Sweetygamer)](https://www.curseforge.com/minecraft/mc-mods/unusual-end)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Shield Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/shield-expansion)
[Repurposed Structures (Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Boat Break Fix [Forge/Fabric/Quilt] (by ElocinDev)](https://www.curseforge.com/minecraft/mc-mods/boat-break-fix)
[Neapolitan (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/neapolitan)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Open Parties and Claims (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims)
[Upgraded Netherite : Ultimerite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-ultimerite)
[The Conjurer (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/the-conjurer)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Paintings ++ (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/paintings)
[MVS - Moog's Voyager Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures)
[NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Trading Post (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/trading-post)
[Twigs (by ninnih_)](https://www.curseforge.com/minecraft/mc-mods/twigs)
[Galosphere (by orcinus73)](https://www.curseforge.com/minecraft/mc-mods/galosphere)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Integrated Dungeons and Structures (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/idas)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Boat Item View (Forge) (by 50ap5ud5)](https://www.curseforge.com/minecraft/mc-mods/boat-item-view-forge)
[Pluto (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/pluto)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Personality (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/personality)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[SwingThroughGrass (by exidex)](https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass)
[More Axolotl Variants API (by AkashiiKun69)](https://www.curseforge.com/minecraft/mc-mods/mavapi)
[Falling Leaves (Forge) (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[Tips (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tips)
[More Babies (Forge & Fabric) (by mammut53m)](https://www.curseforge.com/minecraft/mc-mods/more-babies)
[Unique Enchantments (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/unique-enchantments)
[More Axolotl Variants Mod (by AkashiiKun69)](https://www.curseforge.com/minecraft/mc-mods/mavm)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Raided (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/raided)
[Origins (Forge) (by EdwinMindcraft)](https://www.curseforge.com/minecraft/mc-mods/origins-forge)
[Magnum Torch (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[Visuality: Reforged (by ChannelingCF)](https://www.curseforge.com/minecraft/mc-mods/visuality-reforged)
[Fairy Lights (by pau101)](https://www.curseforge.com/minecraft/mc-mods/fairy-lights)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Kiwi 🥝 (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/kiwi)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[Puzzles Lib (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Duckling (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Grass Overhaul (by ElocinDev)](https://www.curseforge.com/minecraft/mc-mods/grass-overhaul)
[Upgraded Core (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-core)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Festive Delight (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/festive-delight)
[Excavated Variants (by lukebemish)](https://www.curseforge.com/minecraft/mc-mods/excavated-variants)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[Paxi (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/paxi)
[XL Packets (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/xl-packets)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Upgraded Netherite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite)
[Biome Makeover (Forge) (by Lemonszz)](https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Vertical Slabs Compat (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat)
[Item Highlighter [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-highlighter)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Visual Workbench (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Rotten Creatures (by fusionstudiomc)](https://www.curseforge.com/minecraft/mc-mods/rotten-creatures)
[Charm of Undying (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/charm-of-undying)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Drippy Loading Screen [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen)
[Just Zoom [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/just-zoom-forge)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[Earth Mobs (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/earth-mobs)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Nether Depths Upgrade (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/nether-depths-upgrade)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[Nether's Exoticism (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/nethers-exoticism)
[Smarter Farmers (farmers replant) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant)
[Corail Woodcutter Extension (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter-extension)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Skin Layers 3D (Fabric/Forge) (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Unique Enchantments Apex (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/unique-enchantments-apex)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Fairy Dragons! (by kiakkers)](https://www.curseforge.com/minecraft/mc-mods/fairy-dragons)
[PolyLib (by Official_CreeperHost)](https://www.curseforge.com/minecraft/mc-mods/polylib)
[Simple Storage Network (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network)
[Item Filters (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/item-filters)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Dungeons Plus (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/dungeons-plus)
[Elytra Slot (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Gardens of the Dead (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/gardens-of-the-dead)
[No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[It Takes a Pillage (by izofar)](https://www.curseforge.com/minecraft/mc-mods/it-takes-a-pillage)
[Bamboo Everything (Forge/Fabric) (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/bamboo-everything)
[Dynamic Asset Generator (by lukebemish)](https://www.curseforge.com/minecraft/mc-mods/dynamic-asset-generator)
[Better Mods Button (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/better-mods-button)
[Hunter illager (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/hunterillager)
[Dynamic Lights (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights)
[Ore Excavation (by Funwayguy)](https://www.curseforge.com/minecraft/mc-mods/ore-excavation)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Unique Enchantments - Utils (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/unique-enchantments-utils)
[Woodworks (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/woodworks)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
['Dustrial Decor (by BlueDuckYT)](https://www.curseforge.com/minecraft/mc-mods/dustrial-decor)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Plushie Mod (by Link_911)](https://www.curseforge.com/minecraft/mc-mods/plushie-mod)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Abundant Atmosphere (by sheddmerstk)](https://www.curseforge.com/minecraft/mc-mods/abundant-atmosphere)
[Stalwart Dungeons (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons)
[Maiden's Merrymaking - A Minecraft Christmas and Winter Holiday Mod (by maideniles)](https://www.curseforge.com/minecraft/mc-mods/maidens-merry-making)
[Leaves Be Gone (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Frozen Delight (A Farmer's Delight Add-on) (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/frozen-delight)
[RevampedWolf (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/revampedwolf)
[Geode+ [Forge/Fabric] (by YeoXuHang)](https://www.curseforge.com/minecraft/mc-mods/geode-plus)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Upgraded Netherite : Items (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-items)
[Unique Enchantments Base (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/unique-enchantments-base)
[Friends&Foes (Forge) (by faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-forge)
[Sculked (by Ethan_4d)](https://www.curseforge.com/minecraft/mc-mods/sculked)
[Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Spirit (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/spirit)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Dark Paintings (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Origins: Classes (Forge) (by LimonBlaze)](https://www.curseforge.com/minecraft/mc-mods/origins-classes-forge)
[Equipment Compare [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/equipment-compare)
[Better Tridents (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/better-tridents)
[Skinned Lanterns (Forge) (by nuxthefox)](https://www.curseforge.com/minecraft/mc-mods/skinned-lanterns)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Abnormals Delight (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/abnormals-delight)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)
[Delightful (by brdbrn)](https://www.curseforge.com/minecraft/mc-mods/delightful)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Easy Magic (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Bad Mobs (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bad-mobs)) 
There is no crash report and it says exit code 1

**Comment by Virtuoel** [comment] 2023-01-05 21:42
If you have no crash report, please launch your game again so a recent log file is generated, then post the contents of your `.minecraft/logs/latest.log` file in a new comment.

**Comment by saviourom** [comment] 2023-01-05 21:58
[latest.log](https://github.com/Virtuoel/Pehkui/files/10355917/latest.log)

**Comment by Virtuoel** [comment] 2023-01-05 22:11
Aha, I see what the issue is. Thanks for the log.
Looks to be an incompatibility with EarthMobs.
Seems EarthMobs fixed the issue in 5.0.2 (which is sadly only on 1.19.3, so, well, that's unfortunate if your pack doesn't have updates for everything else yet...).

**Comment by Virtuoel** [comment] 2023-01-05 22:24
~~I just realized the fix I added for this sort of issue was only on the Fabric version, not the Forge version too. This should also be fixed on Pehkui's side once I get the next release out.~~
Edit: Oops, got all mixed up and misremembered this, see below comment. You'll probably have to update to 1.19.3 if you want both of the mods.

**Comment by Virtuoel** [comment] 2023-01-05 22:28
Oops, sorry, I got your hopes up about it being fixable in Pehkui. Turns out I read something wrong. Yeah, never mind that message. You'll probably have to update to 1.19.3 if you want to use both of the mods.

**Closed as not planned by Virtuoel** 2023-01-05 22:28 UTC

**Comment by Youhadabadday** [comment] 2023-01-15 21:47
Holy, so THAT was my issue! Thank you so much!
