### ISSUE TITLE
[Suggestion]: Size abilities

### ISSUE THREAD

**Issue by AlbiMousse** [Virtuoel/Pehkui#333] opened 2022-10-27 16:16 UTC
### What is your suggestion?

I don't know if has already been suggested or accepted, but here it goes.
Would it be possible for **larger player to be able to**:

- Crush smaller entities
- Pick up smaller entities
- have the possibility to ming multiple blocks depending on their size (linearly) like pehkui:mining_size

and for **smaller player** to :

- Get crushed by larger entities
- Ride larger entities using like a string (Gulliver)

**Comment by Virtuoel** [comment] 2022-10-30 17:00
Partial duplicate of #183. Out of scope for Pehkui itself, but would be interesting to see another mod as an addon to Pehkui that adds more scale types like this.

**Closed as not planned by Virtuoel** 2022-10-30 17:00 UTC
Labels: enhancement
