### ISSUE TITLE
[Bug]: Crash when opening create world screen

### ISSUE THREAD

**Issue by Jamalam360** [Virtuoel/Pehkui#428] opened 2023-07-10 14:23 UTC
### Minecraft version(s)

1.20.1

### Mod loader

Quilt

### Mod loader version

0.19.2

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

As in title

### Full list of installed mods and their version numbers

Please see the mod table in the logs

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

https://mclo.gs/0WcLcNT

**Comment by Jamalam360** [comment] 2023-07-10 14:24
Sorry for not following your issue template I am in a rush :smile:

**Comment by Virtuoel** [comment] 2023-07-10 14:45
Appears to be caused by ValkyrienSkies redirecting a call that I `@ModifyArg`, specifically [with this](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/blob/1.20.1/main/fabric/src/main/java/org/valkyrienskies/mod/fabric/mixin/server/network/MixinServerPlayerGameMode.java#L31), which results in the vector object from the redirect being added to the arg list.

Ideally [this PR](https://github.com/FabricMC/Mixin/pull/114) that would fix this in Mixin could be merged. Alternatively, VS could probably do a `@ModifyArg` instead of redirecting.

**Comment by Virtuoel** [comment] 2023-07-13 02:20
Should now be resolved with a workaround on Pehkui's end as of Pehkui 3.7.7.

**Closed as completed by Virtuoel** 2023-07-13 02:20 UTC
Labels: bug
