### ISSUE TITLE
[Bug] With Pehkui and Immersive portal installed, my size doesn't change when going through a portal (forge version)

### ISSUE THREAD

**Issue by Ghatos1** [Virtuoel/Pehkui#159] opened 2021-08-08 16:38 UTC
the title says everyting. let's say I'm 2 blocks tall when entering a small portal connected to a bigger one, my size is still two blocks tall when coming out.

**Comment by Virtuoel** [comment] 2021-08-08 16:45
Unfortunately the Forge version of Immersive Portals doesn't support resizing with Pehkui yet. Have to wait for them to update, whenever that may be.

Duplicate of qouteall/ImmersivePortalsModForForge#243

**Closed as completed by Virtuoel** 2021-08-08 16:45 UTC
